########################################################################################
## Student: Brandon Nguyen
## Class:   Advance Python 220 - Jan2019
## Lesson02 - debuging
## This is a debugger_log.txt file that contain all the debug output from console
## From this command: 
##    python -m pdb charges_calc.py -i ./source.json -o ./out.json 2>&1 | tee -a debugger_log.txt
############################################################################################
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(3)<module>()
-> '''
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(10)<module>()
-> def parse_cmd_arguments():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)<module>()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(29)<module>()
-> def calculate_additional_fields(data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(50)<module>()
-> def save_to_json(filename, data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(55)<module>()
-> if __name__ == "__main__":
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(56)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(57)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb)  52  	    with open(filename, 'w') as file:
 53  	        json.dump(data, file)
 54  	
 55  	if __name__ == "__main__":
 56  	    ARGS = parse_cmd_arguments()
 57  ->	    DATA = load_rentals_file(ARGS.input)
 58  	    DATA = calculate_additional_fields(DATA)
 59  	    save_to_json(ARGS.output, DATA)
[EOF]
(Pdb) --Call--
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)load_rentals_file()
-> def load_rentals_file(filename):
(Pdb)  14  	    parser.add_argument('-o', '--output', help='ouput JSON file', required=True)
 15  	
 16  	    return parser.parse_args()
 17  	
 18  	
 19  ->	def load_rentals_file(filename):
 20  	    """ This function is to load the jason data file. """
 21  	    with open(filename) as file:
 22  	        try:
 23  	            data = json.load(file)
 24  	        except:
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(21)load_rentals_file()
-> with open(filename) as file:
(Pdb)  16  	    return parser.parse_args()
 17  	
 18  	
 19  	def load_rentals_file(filename):
 20  	    """ This function is to load the jason data file. """
 21  ->	    with open(filename) as file:
 22  	        try:
 23  	            data = json.load(file)
 24  	        except:
 25  	            exit(0)
 26  	    return data
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(22)load_rentals_file()
-> try:
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(23)load_rentals_file()
-> data = json.load(file)
(Pdb) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5884 column 23 (char 130093)
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(23)load_rentals_file()
-> data = json.load(file)
(Pdb)  18  	
 19  	def load_rentals_file(filename):
 20  	    """ This function is to load the jason data file. """
 21  	    with open(filename) as file:
 22  	        try:
 23  ->	            data = json.load(file)
 24  	        except:
 25  	            exit(0)
 26  	    return data
 27  	
 28  	
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(24)load_rentals_file()
-> except:
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(25)load_rentals_file()
-> exit(0)
(Pdb) SystemExit: 0
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(25)load_rentals_file()
-> exit(0)
(Pdb) Traceback (most recent call last):
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 23, in load_rentals_file
    data = json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5884 column 23 (char 130093)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 57, in <module>
    DATA = load_rentals_file(ARGS.input)
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 25, in load_rentals_file
    exit(0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 23, in load_rentals_file
    data = json.load(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5884 column 23 (char 130093)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 57, in <module>
    DATA = load_rentals_file(ARGS.input)
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 25, in load_rentals_file
    exit(0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1724, in <module>
    pdb.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1716, in main
    pdb.interaction(None, t)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(3)<module>()
-> """
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(10)<module>()
-> def parse_cmd_arguments():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)<module>()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(36)<module>()
-> def calculate_additional_fields(data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(57)<module>()
-> def save_to_json(filename, data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(62)<module>()
-> if __name__ == "__main__":
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(63)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(64)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) --Call--
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)load_rentals_file()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(21)load_rentals_file()
-> with open(filename) as file:
(Pdb)  16  	    return parser.parse_args()
 17  	
 18  	
 19  	def load_rentals_file(filename):
 20  	    """ This function is to load the jason data file. """
 21  ->	    with open(filename) as file:
 22  	        try:
 23  	            data = json.load(file)
 24  	            # Got this error when run debug:
 25  	            # json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes:
 26  	            # line 5884 column 23 (char 130093)
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(22)load_rentals_file()
-> try:
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(23)load_rentals_file()
-> data = json.load(file)
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(33)load_rentals_file()
-> return data
(Pdb) --Return--
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(33)load_rentals_file()->{'RNT001': {'price_per_day': 31, 'product_code': 'PRD80', 'rental_end': '3/22/17', 'rental_start': '6/12/17', ...}, 'RNT002': {'price_per_day': 16, 'product_code': 'PRD11', 'rental_end': '9/30/18', 'rental_start': '7/20/16', ...}, 'RNT003': {'price_per_day': 40, 'product_code': 'PRD22', 'rental_end': '6/4/17', 'rental_start': '2/1/16', ...}, 'RNT004': {'price_per_day': 40, 'product_code': 'PRD86', 'rental_end': '12/7/17', 'rental_start': '8/14/16', ...}, ...}
-> return data
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(65)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) SystemExit: 0
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(65)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1724, in <module>
    pdb.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1716, in main
    pdb.interaction(None, t)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(3)<module>()
-> """
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(10)<module>()
-> def parse_cmd_arguments():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)<module>()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(36)<module>()
-> def calculate_additional_fields(data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(57)<module>()
-> def save_to_json(filename, data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(62)<module>()
-> if __name__ == "__main__":
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(63)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(64)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(65)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) SystemExit: 0
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(65)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1724, in <module>
    pdb.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1716, in main
    pdb.interaction(None, t)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(3)<module>()
-> """
(Pdb) (Pdb) (Pdb) (Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(10)<module>()
-> def parse_cmd_arguments():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)<module>()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(36)<module>()
-> def calculate_additional_fields(data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(57)<module>()
-> def save_to_json(filename, data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(62)<module>()
-> if __name__ == "__main__":
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(63)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(64)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(65)<module>()
-> DATA = calculate_additional_fields(DATA)
(Pdb) --Call--
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(36)calculate_additional_fields()
-> def calculate_additional_fields(data):
(Pdb)  31  	            print("some unknown err")
 32  	            exit(2)
 33  	    return data
 34  	
 35  	
 36  ->	def calculate_additional_fields(data):
 37  	    """
 38  	    What does this do?  Update the "data" with additional data then
 39  	    return "data" set.
 40  	    """
 41  	    for value in data.values():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(41)calculate_additional_fields()
-> for value in data.values():
(Pdb)  36  	def calculate_additional_fields(data):
 37  	    """
 38  	    What does this do?  Update the "data" with additional data then
 39  	    return "data" set.
 40  	    """
 41  ->	    for value in data.values():
 42  	        try:
 43  	            rental_start = datetime.datetime.strptime(value['rental_start'],
 44  	                                                      '%m/%d/%y')
 45  	            rental_end = datetime.datetime.strptime(value['rental_end'],
 46  	                                                    '%m/%d/%y')
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(42)calculate_additional_fields()
-> try:
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(43)calculate_additional_fields()
-> rental_start = datetime.datetime.strptime(value['rental_start'],
(Pdb)  38  	    What does this do?  Update the "data" with additional data then
 39  	    return "data" set.
 40  	    """
 41  	    for value in data.values():
 42  	        try:
 43  ->	            rental_start = datetime.datetime.strptime(value['rental_start'],
 44  	                                                      '%m/%d/%y')
 45  	            rental_end = datetime.datetime.strptime(value['rental_end'],
 46  	                                                    '%m/%d/%y')
 47  	            value['total_days'] = (rental_end - rental_start).days
 48  	            value['total_price'] = value['total_days'] * value['price_per_day']
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(44)calculate_additional_fields()
-> '%m/%d/%y')
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(45)calculate_additional_fields()
-> rental_end = datetime.datetime.strptime(value['rental_end'],
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(46)calculate_additional_fields()
-> '%m/%d/%y')
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(47)calculate_additional_fields()
-> value['total_days'] = (rental_end - rental_start).days
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(48)calculate_additional_fields()
-> value['total_price'] = value['total_days'] * value['price_per_day']
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(49)calculate_additional_fields()
-> value['sqrt_total_price'] = math.sqrt(value['total_price'])
(Pdb) ValueError: math domain error
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(49)calculate_additional_fields()
-> value['sqrt_total_price'] = math.sqrt(value['total_price'])
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(51)calculate_additional_fields()
-> except:
(Pdb)  46  	                                                    '%m/%d/%y')
 47  	            value['total_days'] = (rental_end - rental_start).days
 48  	            value['total_price'] = value['total_days'] * value['price_per_day']
 49  	            value['sqrt_total_price'] = math.sqrt(value['total_price'])
 50  	            value['unit_cost'] = value['total_price'] / value['units_rented']
 51  ->	        except:
 52  	            exit(0)
 53  	
 54  	    return data
 55  	
 56  	
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(52)calculate_additional_fields()
-> exit(0)
(Pdb)  47  	            value['total_days'] = (rental_end - rental_start).days
 48  	            value['total_price'] = value['total_days'] * value['price_per_day']
 49  	            value['sqrt_total_price'] = math.sqrt(value['total_price'])
 50  	            value['unit_cost'] = value['total_price'] / value['units_rented']
 51  	        except:
 52  ->	            exit(0)
 53  	
 54  	    return data
 55  	
 56  	
 57  	def save_to_json(filename, data):
(Pdb) SystemExit: 0
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(52)calculate_additional_fields()
-> exit(0)
(Pdb) Traceback (most recent call last):
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 49, in calculate_additional_fields
    value['sqrt_total_price'] = math.sqrt(value['total_price'])
ValueError: math domain error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 52, in calculate_additional_fields
    exit(0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 49, in calculate_additional_fields
    value['sqrt_total_price'] = math.sqrt(value['total_price'])
ValueError: math domain error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 65, in <module>
    DATA = calculate_additional_fields(DATA)
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 52, in calculate_additional_fields
    exit(0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 94, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 173, in dispatch_exception
    self.user_exception(frame, arg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 312, in user_exception
    self.interaction(frame, exc_traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1724, in <module>
    pdb.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1716, in main
    pdb.interaction(None, t)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
> /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(3)<module>()
-> """
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(4)<module>()
-> import argparse
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(5)<module>()
-> import json
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(6)<module>()
-> import datetime
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(7)<module>()
-> import math
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(10)<module>()
-> def parse_cmd_arguments():
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(19)<module>()
-> def load_rentals_file(filename):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(36)<module>()
-> def calculate_additional_fields(data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(62)<module>()
-> def save_to_json(filename, data):
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(67)<module>()
-> if __name__ == "__main__":
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(68)<module>()
-> ARGS = parse_cmd_arguments()
(Pdb) > /Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py(69)<module>()
-> DATA = load_rentals_file(ARGS.input)
(Pdb) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1697, in main
    pdb._runscript(mainpyfile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 69, in <module>
    DATA = load_rentals_file(ARGS.input)
  File "/Users/bnguyen/py220BV201901/students/bnguyen/lessons/lesson02/assignment/code/charges_calc.py", line 52, in calculate_additional_fields
    value['total_price'] = value['total_days'] * value['pricqe_per_day']
KeyError: 'pricqe_per_day'
start_date > end_date issue: {'product_code': 'PRD80', 'units_rented': 8, 'price_per_day': 31, 'rental_start': '6/12/17', 'rental_end': '3/22/17'}
Uncaught exception. Entering post mortem debugging
